// channels
import './channels/lock';
import './channels/unlock';
// moderation
import './moderation/ban';
import './moderation/kick';
import './moderation/mute';
import './moderation/timeout';
import './moderation/unban';
import './moderation/unmute';
// roles
import './roles/addrole';
import './roles/removerole';
// utils
import './util/clear';
import './util/ping';